config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :videos
  resources :youtubes

  #  Pages routes
  root 'pages#home'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/pages/contact', to: 'pages#submit_contact_info', via: 'post'
  match '/pages/contact', to: 'pages#contact_success', via: 'get'
  match '/pages/search', to: 'pages#search', via: 'get'
  match '/pages/status', to: 'pages#status', via: 'get'
  match '/sitemap', to: 'pages#sitemap', via: 'get'
  match '/advertise', to: 'pages#advertise', via: 'get'
  match '/about', to: 'pages#about', via: 'get'
  match '/subscribe', to: 'pages#subscribe', via: 'get'
  match '/terms', to: 'pages#terms', via: 'get'
  match '/privacy', to: 'pages#privacy', via: 'get'
  match '/giveaway', to: 'pages#giveaway', via: 'get'

  # Videos routes
  match '/watch', to: 'videos#watch', via: 'get'
  match '/accept', to: 'videos#accept', via: 'get'
  match '/processed', to: 'videos#processed', via: 'get'
  match '/videos/new/manual', to: 'videos#manual', via: 'get'
  match '/submit', to: 'videos#submit', via: 'get'



  # Admin routes
  match '/admin', to: 'admins#index', via: 'get'
  match '/admin/login', to: 'sessions#new', via: 'get'
  match '/admin/logout', to: 'sessions#destroy', via: 'DELETE'
  match '/admin/login', to: 'sessions#create', via: 'post'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	attr_accessor :current_password

	before_save { self.email = email.downcase }
	validates :user_name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 100}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password

	validates :password, presence: true, length: {minimum: 6}

	def self.new_token
		SecureRandom.urlsafe_base64
	end
	def self.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def remember
		@remember_token = User.new_token()
		update_attribute(:remember_digest, User.digest(@remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /users
  # GET /users.json
  def index
    @logged_in = logged_in?
    if @logged_in
      @users = User.all
    else 
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user  = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
    @users_info = {user: @user}
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      @users_info = {user: @user}
      if @user.save
        @users_info['success'] = true
        format.html { render action: 'new' }
        format.json { render json: @users_info }
      else
         @users_info['success'] = false
         format.html { render action: 'new' }
        format.json { render json: @users_info }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if !user_params[:password].blank? && !user_params[:password_confirmation].blank? && user_params[:current_password].blank?
      raise Exception.new('You must enter your current password to change password')
    end
    if (!@user.authenticate(user_params[:current_password]))
      raise Exception.new('Invalid current password')
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { render action: 'edit' }
        format.json { render json: {user: @user, success: true }}
      else
        format.html { render action: 'edit' }
        format.json { render json: {user: @user, success: false }}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :current_password, :super_admin)
    end
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit User')%>
<div class = "container-fluid container-admin-users">
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
      <%= react_component("UsersForm",  props: { usersInfo: {user: @user} }, prerender: true) %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'users') %>
<div class="container-fluid container-admin-users">
  <div class="row">
    <div class="col-xs-12">
      <%= react_component("Users",  props: { users: @users }, prerender: true) %>
    </div>
  </div>    
</div>

app/views/users/new.html.erb
<% provide(:title, 'Upload Video')%>
<div class = "container-fluid container-admin-users">
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
      <%= react_component("UsersForm",  props: { usersInfo: @users_info }, prerender: true) %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container-fluid container-contact">
	<div class="row">
		<div class="col-md-2 col-md-offset-5">
			<div class="alert alert-warning">
			 <p id="notice"><%= notice %></p>
			 <%= link_to 'Sign in', admin_login_path %>
			</div>
		</div>	
	</div>
</div>