config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :videos
  resources :youtubes

  #  Pages routes
  root 'pages#home'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/pages/contact', to: 'pages#submit_contact_info', via: 'post'
  match '/pages/contact', to: 'pages#contact_success', via: 'get'
  match '/pages/search', to: 'pages#search', via: 'get'
  match '/pages/status', to: 'pages#status', via: 'get'
  match '/sitemap', to: 'pages#sitemap', via: 'get'
  match '/advertise', to: 'pages#advertise', via: 'get'
  match '/about', to: 'pages#about', via: 'get'
  match '/subscribe', to: 'pages#subscribe', via: 'get'
  match '/terms', to: 'pages#terms', via: 'get'
  match '/privacy', to: 'pages#privacy', via: 'get'
  match '/giveaway', to: 'pages#giveaway', via: 'get'

  # Videos routes
  match '/watch', to: 'videos#watch', via: 'get'
  match '/accept', to: 'videos#accept', via: 'get'
  match '/processed', to: 'videos#processed', via: 'get'
  match '/videos/new/manual', to: 'videos#manual', via: 'get'
  match '/submit', to: 'videos#submit', via: 'get'



  # Admin routes
  match '/admin', to: 'admins#index', via: 'get'
  match '/admin/login', to: 'sessions#new', via: 'get'
  match '/admin/logout', to: 'sessions#destroy', via: 'DELETE'
  match '/admin/login', to: 'sessions#create', via: 'post'

end

app/models/youtube.rb
class Youtube < ActiveRecord::Base
  include PgSearch::Model

  # Association 
  has_many :video_views, :foreign_key => 'youtube_url', :primary_key => 'url'

	scope :same_meta_data_as, -> (meta_data) {where meta_data: meta_data}
  scope :same_url_as, -> (url) {where url: url}
  pg_search_scope :search, against: [:title]
end

app/controllers/youtubes_controller.rb
class YoutubesController < ApplicationController
  load_and_authorize_resource
  before_action :set_youtube, only: [:show, :edit, :update, :destroy]

  # GET /youtubes
  # GET /youtubes.json
  def index
    @youtubes = Youtube.all
  end

  # GET /youtubes/1
  # GET /youtubes/1.json
  def show
    @youtube   = Youtube.find params[:id]
  end

  # GET /youtubes/new
  def new
    @youtube = Youtube.new
  end

  # GET /youtubes/1/edit
  def edit
  end

  # POST /youtubes
  # POST /youtubes.json
  def create
    @youtube = Youtube.new(youtube_params)

    respond_to do |format|
      if @youtube.save
        format.html { redirect_to @youtube, notice: 'Youtube was successfully created.' }
        format.json { render action: 'show', status: :created, location: @youtube }
      else
        format.html { render action: 'new' }
        format.json { render json: @youtube.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /youtubes/1
  # PATCH/PUT /youtubes/1.json
  def update
    respond_to do |format|
      if @youtube.update(youtube_params)
        format.html { redirect_to @youtube, notice: 'Youtube was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @youtube.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /youtubes/1
  # DELETE /youtubes/1.json
  def destroy
    @youtube.destroy
    respond_to do |format|
      format.html { redirect_to youtubes_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_youtube
      @youtube = Youtube.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def youtube_params
      params.require(:youtube).permit(:url, :title, :date, :meta_data)
    end
end

app/views/youtubes/_form.html.erb
<%= form_for(@youtube) do |f| %>
  <% if @youtube.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@youtube.errors.count, "error") %> prohibited this youtube from being saved:</h2>

      <ul>
      <% @youtube.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :meta_data %><br>
    <%= f.text_field :meta_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/youtubes/edit.html.erb
<h1>Editing youtube</h1>

<%= render 'form' %>

<%= link_to 'Show', @youtube %> |
<%= link_to 'Back', youtubes_path %>

app/views/youtubes/index.html.erb
<h1>Listing youtubes</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Date</th>
      <th>Meta data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @youtubes.each do |youtube| %>
      <tr>
        <td><%= youtube.url %></td>
        <td><%= youtube.title %></td>
        <td><%= youtube.date %></td>
        <td><%= youtube.meta_data %></td>
        <td><%= link_to 'Show', youtube %></td>
        <td><%= link_to 'Edit', edit_youtube_path(youtube) %></td>
        <td><%= link_to 'Destroy', youtube, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Youtube', new_youtube_path %>

app/views/youtubes/new.html.erb
<h1>New youtube</h1>

<%= render 'form' %>

<%= link_to 'Back', youtubes_path %>

app/views/youtubes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @youtube.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @youtube.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @youtube.date %>
</p>

<p>
  <strong>Meta data:</strong>
  <%= @youtube.meta_data %>
</p>

<%= link_to 'Edit', edit_youtube_path(@youtube) %> |
<%= link_to 'Back', youtubes_path %>